import nodemailer from "nodemailer";
import { loadConfig } from "../config";
import path from "path";

let config = loadConfig();
const transporter = nodemailer.createTransport({
  host: config.email.smtp.host,
  port: config.email.smtp.port,
  secure: config.email.smtp.secure,
  auth: {
    user: config.email.auth.user,
    pass: config.email.auth.pass,
  },
});

export interface EmailOptions {
  to: string;
  domain: string;
  pdfPath: string;
}

export const sendAuditEmail = async (options: EmailOptions): Promise<void> => {
  const { to, domain, pdfPath } = options;
  const pdfFilename = path.basename(pdfPath);

  console.log(`\n📧 Preparing to send email to ${to}...`);

  try {
    const info = await transporter.sendMail({
      from: config.email.defaults.from,
      to: to,
      subject: `A Few Reasons Why ${domain} Might Be Losing to Competitors on Google`,
      html: `
                <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;">
                    <div style="background-color: #1e293b; color: white; padding: 20px;">
                        <h2 style="margin: 0;">VectorSEO Analysis</h2>
                    </div>
                    <div style="padding: 20px;">
                        <h3 style="color: #1e293b;">Complimentary SEO Report for ${domain}</h3>
                        <p>Hello,</p>
                        <p>While researching businesses in your industry, our team performed a complimentary technical SEO analysis on <strong>${domain}</strong>, and we discovered several key opportunities for improvement.</p>
                        <p>We've attached our findings in a detailed, multi-page report. It's free for you to use with no obligation. It outlines the "what" and the "why" behind some of the technical issues that may be preventing your site from ranking higher on Google.</p>
                        <p>We believe in providing value upfront. If you would like to schedule a brief consultation to discuss the "how" of implementing these fixes, we would be happy to help.</p>
                        <a href="mailto:${config.email.auth.user}?subject=Re: SEO Audit for ${domain}" style="display: inline-block; background-color: #2563eb; color: white; padding: 12px 20px; text-decoration: none; border-radius: 5px; margin-top: 10px;">
                            Schedule a Consultation
                        </a>
                        <p style="margin-top: 30px;">Best regards,</p>
                        <p><strong>The Team at VectorSEO</strong></p>
                    </div>
                    <div style="background-color: #f8fafc; color: #94a3b8; padding: 15px; text-align: center; font-size: 12px;">
                        <p>Generated by VectorSEO</p>
                    </div>
                </div>
            `,
      attachments: [
        {
          filename: pdfFilename,
          path: pdfPath,
          contentType: "application/pdf",
        },
      ],
    });

    console.log(`✅ Email sent successfully! Message ID: ${info.messageId}`);
  } catch (error) {
    console.error(`❌ Failed to send email:`, error);
  }
};
